module: MaterialMotion
module_version: 2.0.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotion.xcworkspace
  - -scheme
  - MaterialMotion
github_url: https://github.com/material-motion/material-motion-swift
github_file_prefix: https://github.com/material-motion/material-motion-swift/tree/v2.0.0
